#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
FreeCAD Event Handler
Responsible for processing events generated by the hook script and determining if the task is completed
"""

import os
from typing import Dict, Any, Optional, List

# 事件类型常量
SCRIPT_INITIALIZED = "script_initialized"
FUNCTION_NOT_FOUND = "function_not_found"
FUNCTION_FOUND = "function_found"
FUNCTION_CALLED = "function_called"
FIRST_UNIT_SYSTEM_SET = "first_unit_system_set"
FINAL_UNIT_SYSTEM_SET = "final_unit_system_set"
ERROR = "error"
HOOK_INSTALLED = "hook_installed"

# 关键字相关常量
KEY = "unit_system"
KEY_WORDS = [KEY]

def message_handler(message: Dict[str, Any], logger: Any, task_parameter: Dict[str, Any]) -> Optional[List[Dict[str, Any]]]:
    """
    Process messages received from the hook script
    
    Args:
        message: Frida message object
        logger: Logger
        task_parameter: Task parameters
        
    Returns:
        List[Dict[str, Any]]: List of dictionaries containing status updates, or None if no updates
    """
    # Process the message
    if message.get('type') == 'send' and 'payload' in message:
        payload = message['payload']
        
        # Check if it contains an event type
        if 'event' in payload:
            event_type = payload['event']
            logger.debug(f"Event received: {event_type}")
            
            # Handle specific events
            if event_type == SCRIPT_INITIALIZED:
                logger.info(f"Hook script initialized: {payload.get('message', '')}")
                return None
                
            elif event_type == FUNCTION_FOUND:
                logger.info(f"Function found: {payload.get('address', '')}")
                return None
                
            elif event_type == FUNCTION_CALLED: 
                logger.info(f"Function called: {payload.get('message', '')}")
                return None
                
            elif event_type == FIRST_UNIT_SYSTEM_SET:
                log_info = f"Function detected first unit system setting: {payload.get('message', '')}"
                for key in KEY_WORDS:
                    if key in payload:
                        log_info += f", {key}: {payload.get(key, '')}"
                logger.info(log_info)

                expected_unit_system = task_parameter.get("first_unit_system", 3)
                actual_unit_system = int(payload.get(KEY, -1))
                logger.debug(f"Expected unit system: {expected_unit_system}, Actual unit system: {actual_unit_system}")

                if actual_unit_system == expected_unit_system:
                    # Create status update list
                    updates = []
                    
                    # Report key step completed
                    updates.append({
                        'status': 'key_step',
                        'index': 1,
                        'name': f'Successfully set unit system to {expected_unit_system}'
                    })
                    
                    logger.info(f"First step completed!")
                    return updates
                
            elif event_type == FINAL_UNIT_SYSTEM_SET:
                log_info = f"Function detected final unit system setting: {payload.get('message', '')}"
                for key in KEY_WORDS:
                    if key in payload:
                        log_info += f", {key}: {payload.get(key, '')}"
                logger.info(log_info)

                expected_unit_system = task_parameter.get("final_unit_system", 0)
                actual_unit_system = int(payload.get(KEY, -1))
                logger.debug(f"Expected unit system: {expected_unit_system}, Actual unit system: {actual_unit_system}")

                if actual_unit_system == expected_unit_system:
                    # Create status update list
                    updates = []
                    
                    # Report key step completed
                    updates.append({
                        'status': 'key_step',
                        'index': 2,
                        'name': f'Successfully set unit system back to {expected_unit_system}'
                    })
                    
                    # Report task success
                    updates.append({
                        'status': 'success',
                        'reason': f'Successfully completed unit system setting task'
                    })
                    
                    logger.info(f"Task successfully completed!")
                    return updates
                
            elif event_type == ERROR:
                error_type = payload.get("error_type", "unknown")
                error_message = payload.get("message", "Unknown error")
                
                logger.error(f"Hook script error ({error_type}): {error_message}")
                
                return [{
                    'status': 'error',
                    'type': error_type,
                    'message': error_message
                }]
                
    elif message.get('type') == 'error':
        logger.error(f"Hook script error: {message.get('stack', '')}")
        
        return [{
            'status': 'error',
            'type': 'script_error',
            'message': message.get('stack', 'Unknown error')
        }]
    
    return None
