#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
QGIS Layer Notes Addition Event Handler
Responsible for processing events generated by hook scripts and updating evaluation metrics
"""

from typing import Dict, Any, Optional, List

def message_handler(message: Dict[str, Any], logger: Any, task_parameter: Dict[str, Any]) -> Optional[List[Dict[str, Any]]]:
    """
    Process messages received from hook scripts
    
    Args:
        message: Frida message object
        logger: Logger object
        task_parameter: Task parameters
        
    Returns:
        Optional[List[Dict[str, Any]]]: Returns status list if task status is updated, otherwise None
    """

    # Process message
    if message.get('type') == 'send' and 'payload' in message:
        payload = message['payload']
        
        # Check if event type is included
        if 'event' in payload:
            event_type = payload['event']
            logger.debug(f"Event received: {event_type}")
            
            # Handle specific events
            if event_type == "script_initialized":
                logger.info(f"Hook script initialized: {payload.get('message', '')}")
                return None
                
            elif event_type == "set_function_found":
                logger.info(f"Found layer notes function: {payload.get('address', '')}")
                return None
                
            elif event_type == "layer_set":
                layer_name = payload.get("name", "")
                logger.info(f"Detected layer for notes addition: {layer_name}")
                
                # Check if layer name matches expectation
                expected_layer_name = task_parameter.get("LayerName", "")
                logger.debug(f"Comparing layer names - Detected: {layer_name}, Expected: {expected_layer_name}")
                
                # Determine if detected layer name matches expectation
                if expected_layer_name.lower() in layer_name.lower():
                    logger.info("Layer name for notes addition matches expected target!")                    
                    # Return key step
                    return [{"status": "key_step", "index": 1, "name": "Operating on expected layer"}]
                else:
                    logger.info(f"Layer name for notes addition does not match expectation. Expected: {expected_layer_name}, Actual: {layer_name}")
                
            elif event_type == "notes_set":
                layer_name = payload.get("layer", "")
                notes_text = payload.get("notes", "")
                notes_html = payload.get("notes_html", "")
                
                logger.info(f"Detected notes addition for layer {layer_name}: {notes_text}")
                
                # Check if layer name and notes content match expectations
                expected_layer_name = task_parameter.get("LayerName", "")
                expected_notes = task_parameter.get("notes", "")
                
                # Clean and compare notes content
                detected_notes = notes_text.strip().lower()
                expected_notes = expected_notes.strip().lower()
                
                # Determine if detected notes content matches expectation
                layer_match = expected_layer_name.lower() in layer_name.lower()
                notes_match = expected_notes in detected_notes
                
                if layer_match and notes_match:
                    logger.info(f"Layer notes addition matches expectation! Layer: {layer_name}, Notes: {notes_text}")                    
                    # Return key step and success status
                    return [
                        {"status": "key_step", "index": 2, "name": "Expected notes set"},
                        {"status": "success", "reason": f"Successfully added notes to layer {layer_name}: {notes_text}"}
                    ]
                else:
                    if not layer_match:
                        logger.info(f"Layer does not match expectation. Expected: {expected_layer_name}, Actual: {layer_name}")
                    if not notes match:
                        logger.info(f"Notes content does not match expectation. Expected: {expected_notes}, Actual: {detected_notes}")
                
            elif event_type == "error":
                error_type = payload.get("error_type", "unknown")
                error_message = payload.get("message", "Unknown error")
                logger.error(f"Hook script error ({error_type}): {error_message}")
                
                # Return error status
                return [{
                    "status": "error",
                    "type": error_type,
                    "message": error_message
                }]
                
    elif message.get('type') == 'error':
        stack = message.get('stack', '')
        logger.error(f"Hook script error: {stack}")
        
        # Return error status
        return [{
            "status": "error",
            "type": "script_error",
            "message": "Hook script execution error",
            "stack_trace": stack
        }]
    
    return None
