#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
FreeCAD Cone with Hemispherical Cutout Event Handler
Responsible for processing events generated by the hook script and updating evaluation metrics
"""

from typing import Dict, Any, Optional, List

# Event type constants
SCRIPT_INITIALIZED = "script_initialized"
FUNCTION_NOT_FOUND = "function_not_found"
FUNCTION_FOUND = "function_found"
FUNCTION_CALLED = "function_called"
FUNCTION_KEY_WORD_DETECTED = "function_key_word_detected"
ERROR = "error"
HOOK_INSTALLED = "hook_installed"

# Keyword-related constants
CONE_RADIUS1 = "cone_radius1"
CONE_RADIUS2 = "cone_radius2"
CONE_HEIGHT = "cone_height"
SPHERE_RADIUS = "sphere_radius"
SPHERE_POSITION_X = "sphere_position_x"
SPHERE_POSITION_Y = "sphere_position_y"
SPHERE_POSITION_Z = "sphere_position_z"
HAS_SPHERE_CUT = "has_sphere_cut"

def execute_python_code(code: str, logger: Any) -> Dict[str, Any]:
    """
    Execute Python code and return the result
    
    Args:
        code: Python code to execute
        logger: Logger instance
        
    Returns:
        Dict[str, Any]: Execution result
    """
    try:
        # Create a new namespace to execute the code
        namespace = {}
        exec(code, namespace)
        result = namespace.get('result', None)
        
        if result is None:
            logger.warning("Cone with hemispherical cutout object not found")
            return None
            
        # Validate result format
        required_keys = [
            CONE_RADIUS1, CONE_RADIUS2, CONE_HEIGHT, 
            SPHERE_RADIUS, SPHERE_POSITION_X, SPHERE_POSITION_Y, 
            SPHERE_POSITION_Z, HAS_SPHERE_CUT
        ]
        if not all(key in result for key in required_keys):
            logger.error(f"Result is missing required keys: {required_keys}")
            return None
            
        return result
    except Exception as e:
        logger.error(f"Error executing Python code: {str(e)}")
        return None

def message_handler(message: Dict[str, Any], logger: Any, task_parameter: Dict[str, Any]) -> Optional[List[Dict[str, Any]]]:
    """
    Handle messages received from the hook script
    
    Args:
        message: Frida message object
        logger: Logger instance
        task_parameter: Task parameters
        
    Returns:
        Optional[List[Dict[str, Any]]]: List of status updates, or None if no updates
    """
    updates = []
    
    if message.get('type') == 'send' and 'payload' in message:
        payload = message['payload']
        
        if 'event' in payload:
            event_type = payload['event']
            logger.debug(f"Received event: {event_type}")
            
            if event_type == SCRIPT_INITIALIZED:
                logger.info(f"Hook script initialized: {payload.get('message', '')}")
                
            elif event_type == FUNCTION_FOUND:
                logger.info(f"Function found: {payload.get('address', '')}")
                
            elif event_type == FUNCTION_CALLED:
                logger.info(f"Function called: {payload.get('message', '')}")
                # Update the first key step status
                updates.append({
                    'status': 'key_step',
                    'index': 1,
                    'name': 'Save document'
                })
                
            elif event_type == FUNCTION_KEY_WORD_DETECTED:
                # Execute Python code and get the result
                code = payload.get('code', '')
                filename = payload.get('filename', '')
                expected_path = task_parameter.get("source_path", "") + task_parameter.get("filename", "")
                logger.info(f"Keyword detected, document path: {filename}, expected document path: {expected_path}")
                
                if filename == expected_path:
                    result = execute_python_code(code, logger)
                    if result:
                        # Check if the cone with spherical cutout parameters meet expectations
                        expected_cone_radius1 = task_parameter.get(CONE_RADIUS1, 25.0)
                        expected_cone_radius2 = task_parameter.get(CONE_RADIUS2, 10.0)
                        expected_cone_height = task_parameter.get(CONE_HEIGHT, 40.0)
                        expected_sphere_radius = task_parameter.get(SPHERE_RADIUS, 15.0)
                        expected_sphere_position_x = task_parameter.get(SPHERE_POSITION_X, 0.0)
                        expected_sphere_position_y = task_parameter.get(SPHERE_POSITION_Y, 0.0)
                        expected_sphere_position_z = task_parameter.get(SPHERE_POSITION_Z, 25.0)

                        actual_cone_radius1 = result[CONE_RADIUS1]
                        actual_cone_radius2 = result[CONE_RADIUS2]
                        actual_cone_height = result[CONE_HEIGHT]
                        actual_sphere_radius = result[SPHERE_RADIUS]
                        actual_sphere_position_x = result[SPHERE_POSITION_X]
                        actual_sphere_position_y = result[SPHERE_POSITION_Y]
                        actual_sphere_position_z = result[SPHERE_POSITION_Z]
                        actual_has_sphere_cut = result[HAS_SPHERE_CUT]

                        # Log key parameters
                        logger.info(f"Task parameter check: Expected cone bottom radius={expected_cone_radius1}, top radius={expected_cone_radius2}, height={expected_cone_height}")
                        logger.info(f"Expected spherical cutout: radius={expected_sphere_radius}, position=({expected_sphere_position_x}, {expected_sphere_position_y}, {expected_sphere_position_z})")
                        logger.info(f"Actual parameters: Actual cone bottom radius={actual_cone_radius1}, top radius={actual_cone_radius2}, height={actual_cone_height}")
                        logger.info(f"Actual spherical cutout: radius={actual_sphere_radius}, position=({actual_sphere_position_x}, {actual_sphere_position_y}, {actual_sphere_position_z}), " +
                                   f"Has spherical cutout: {actual_has_sphere_cut}")

                        try:
                            # Attempt to extract numerical values (handle possible units)
                            actual_cone_radius1_value = float(str(actual_cone_radius1).split()[0]) if isinstance(actual_cone_radius1, str) else float(actual_cone_radius1)
                            actual_cone_radius2_value = float(str(actual_cone_radius2).split()[0]) if isinstance(actual_cone_radius2, str) else float(actual_cone_radius2)
                            actual_cone_height_value = float(str(actual_cone_height).split()[0]) if isinstance(actual_cone_height, str) else float(actual_cone_height)
                            
                            actual_sphere_radius_value = float(str(actual_sphere_radius).split()[0]) if isinstance(actual_sphere_radius, str) else float(actual_sphere_radius)
                            actual_sphere_position_x_value = float(str(actual_sphere_position_x).split()[0]) if isinstance(actual_sphere_position_x, str) else float(actual_sphere_position_x)
                            actual_sphere_position_y_value = float(str(actual_sphere_position_y).split()[0]) if isinstance(actual_sphere_position_y, str) else float(actual_sphere_position_y)
                            actual_sphere_position_z_value = float(str(actual_sphere_position_z).split()[0]) if isinstance(actual_sphere_position_z, str) else float(actual_sphere_position_z)
                            
                            # Allow a certain margin of error (0.01%)
                            cone_radius1_error = abs((actual_cone_radius1_value - expected_cone_radius1) / expected_cone_radius1) <= 0.0001
                            cone_radius2_error = abs((actual_cone_radius2_value - expected_cone_radius2) / expected_cone_radius2) <= 0.0001
                            cone_height_error = abs((actual_cone_height_value - expected_cone_height) / expected_cone_height) <= 0.0001
                            
                            sphere_radius_error = abs((actual_sphere_radius_value - expected_sphere_radius) / expected_sphere_radius) <= 0.0001
                            # Position coordinates allow a certain margin of error (absolute error 1.0mm)
                            sphere_position_x_error = abs(actual_sphere_position_x_value - expected_sphere_position_x) <= 1.0
                            sphere_position_y_error = abs(actual_sphere_position_y_value - expected_sphere_position_y) <= 1.0
                            sphere_position_z_error = abs(actual_sphere_position_z_value - expected_sphere_position_z) <= 1.0
                            
                            has_sphere_cut_correct = actual_has_sphere_cut
                        except Exception as e:
                            logger.error(f"Error comparing parameters: {str(e)}")
                            cone_radius1_error = False
                            cone_radius2_error = False
                            cone_height_error = False
                            sphere_radius_error = False
                            sphere_position_x_error = False
                            sphere_position_y_error = False
                            sphere_position_z_error = False
                            has_sphere_cut_correct = False
                        
                        cone_correct = cone_radius1_error and cone_radius2_error and cone_height_error
                        sphere_correct = (sphere_radius_error and 
                                         sphere_position_x_error and 
                                         sphere_position_y_error and
                                         sphere_position_z_error and
                                         has_sphere_cut_correct)
                        
                        if cone_correct and sphere_correct:
                            # Update the second key step status
                            updates.append({
                                'status': 'key_step',
                                'index': 2,
                                'name': 'Successfully created and saved cone with hemispherical cutout'
                            })
                            
                            # Task successfully completed
                            updates.append({
                                'status': 'success',
                                'reason': 'Successfully created and saved cone with hemispherical cutout that meets requirements'
                            })
                        else:
                            logger.warning(f"Parameter validation failed: " + 
                                          f"Cone correct: {cone_correct}, " +
                                          f"Spherical cutout correct: {sphere_correct}")
                
            elif event_type == ERROR:
                error_type = payload.get("error_type", "unknown")
                error_message = payload.get("message", "Unknown error")
                
                logger.error(f"Hook script error ({error_type}): {error_message}")
                
                # Record error event
                updates.append({
                    'status': 'error',
                    'type': error_type,
                    'message': error_message
                })
                
    elif message.get('type') == 'error':
        logger.error(f"Hook script error: {message.get('stack', '')}")
        
        # Record error event
        updates.append({
            'status': 'error',
            'type': 'script_error',
            'message': message.get('stack', 'Unknown error')
        })
    
    return updates if updates else None
