#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
QGIS Project Loading Event Handler
Responsible for processing events generated by hook scripts and updating evaluation metrics
"""

import os
from typing import Dict, Any, Optional, List

def message_handler(message: Dict[str, Any], logger: Any, task_parameter: Dict[str, Any]) -> Optional[List[Dict[str, Any]]]:
    """
    Process messages received from hook scripts
    
    Args:
        message: Frida message object
        logger: Logger
        task_parameter: Task parameters
        
    Returns:
        Optional[List[Dict[str, Any]]]: Return status list if task status is updated, otherwise return None
    """

    # Process message
    if message.get('type') == 'send' and 'payload' in message:
        payload = message['payload']
        
        # Check if event type is included
        if 'event' in payload:
            event_type = payload['event']
            logger.debug(f"Received event: {event_type}")
            
            # Handle specific events
            if event_type == "script_initialized":
                logger.info(f"Hook script initialized: {payload.get('message', '')}")
                return None
                
            elif event_type == "load_function_found":
                logger.info(f"Found project loading function: {payload.get('address', '')}")
                return None
                
            elif event_type == "project_loaded":
                path = payload.get("path", "")
                logger.info(f"Project loading detected: {path}")
                
                # Check if project path matches expectation
                expected_path = task_parameter.get("load_path", "")
                logger.debug(f"Comparing project paths - Detected: {path}, Expected: {expected_path}")
                
                # Determine if detected path matches expectation
                if expected_path.lower() in path.lower() or os.path.basename(expected_path).lower() in path.lower():
                    logger.info("Loaded project path matches expected target!")                    
                    # Return key step and success status
                    return [
                        {"status": "key_step", "index": 1, "name": "Project loaded"},
                        {"status": "success", "reason": f"Successfully loaded project: {path}"}
                    ]
                else:
                    logger.info(f"Loaded project path does not match expectation. Expected: {expected_path}, Actual: {path}")
                
            elif event_type == "error":
                error_type = payload.get("error_type", "unknown")
                error_message = payload.get("message", "Unknown error")
                logger.error(f"Hook script error ({error_type}): {error_message}")
                
                # Return error status
                return [{
                    "status": "error",
                    "type": error_type,
                    "message": error_message
                }]
                
    elif message.get('type') == 'error':
        stack = message.get('stack', '')
        logger.error(f"Hook script error: {stack}")
        
        # Return error status
        return [{
            "status": "error",
            "type": "script_error",
            "message": "Hook script execution error",
            "stack_trace": stack
        }]
    
    return None
