#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
FreeCAD Octagonal Prism with Central Circular Hole Event Handler
Responsible for processing events generated by the hook script and updating evaluation metrics
"""

from typing import Dict, Any, Optional, List

# Event type constants
SCRIPT_INITIALIZED = "script_initialized"
FUNCTION_NOT_FOUND = "function_not_found"
FUNCTION_FOUND = "function_found"
FUNCTION_CALLED = "function_called"
FUNCTION_KEY_WORD_DETECTED = "function_key_word_detected"
ERROR = "error"
HOOK_INSTALLED = "hook_installed"

# Keyword-related constants
PRISM_RADIUS = "prism_radius"
PRISM_HEIGHT = "prism_height"
HOLE_RADIUS = "hole_radius"
SIDES_COUNT = "sides_count"
HAS_HOLE = "has_hole"

def execute_python_code(code: str, logger: Any) -> Dict[str, Any]:
    """
    Execute Python code and return the result
    
    Args:
        code: Python code to execute
        logger: Logger object
        
    Returns:
        Dict[str, Any]: Execution result
    """
    try:
        # Create a new namespace to execute the code
        namespace = {}
        exec(code, namespace)
        result = namespace.get('result', None)
        
        if result is None:
            logger.warning("Octagonal prism with central circular hole object not found")
            return None
            
        # Validate result format
        required_keys = [
            PRISM_RADIUS, PRISM_HEIGHT, HOLE_RADIUS, SIDES_COUNT, HAS_HOLE
        ]
        if not all(key in result for key in required_keys):
            logger.error(f"Result missing required keys: {required_keys}")
            return None
            
        return result
    except Exception as e:
        logger.error(f"Error executing Python code: {str(e)}")
        return None

def message_handler(message: Dict[str, Any], logger: Any, task_parameter: Dict[str, Any]) -> Optional[List[Dict[str, Any]]]:
    """
    Process messages received from the hook script
    
    Args:
        message: Frida message object
        logger: Logger object
        task_parameter: Task parameters
        
    Returns:
        Optional[List[Dict[str, Any]]]: List of status updates, or None if no updates
    """
    updates = []
    
    if message.get('type') == 'send' and 'payload' in message:
        payload = message['payload']
        
        if 'event' in payload:
            event_type = payload['event']
            logger.debug(f"Event received: {event_type}")
            
            if event_type == SCRIPT_INITIALIZED:
                logger.info(f"Hook script initialized: {payload.get('message', '')}")
                
            elif event_type == FUNCTION_FOUND:
                logger.info(f"Function found: {payload.get('address', '')}")
                
            elif event_type == FUNCTION_CALLED:
                logger.info(f"Function called: {payload.get('message', '')}")
                # Update first key step status
                updates.append({
                    'status': 'key_step',
                    'index': 1,
                    'name': 'Document saved'
                })
                
            elif event_type == FUNCTION_KEY_WORD_DETECTED:
                # Execute Python code and get results
                code = payload.get('code', '')
                filename = payload.get('filename', '')
                expected_path = task_parameter.get("source_path", "") + task_parameter.get("filename", "")
                logger.info(f"Detected keywords, document path: {filename}, expected document path: {expected_path}")
                
                if filename == expected_path:
                    result = execute_python_code(code, logger)
                    if result:
                        # Check if octagonal prism parameters meet expectations
                        expected_prism_radius = task_parameter.get(PRISM_RADIUS, 50.0)
                        expected_prism_height = task_parameter.get(PRISM_HEIGHT, 20.0)
                        expected_hole_radius = task_parameter.get(HOLE_RADIUS, 15.0)
                        expected_sides_count = task_parameter.get(SIDES_COUNT, 8)

                        actual_prism_radius = result[PRISM_RADIUS]
                        actual_prism_height = result[PRISM_HEIGHT]
                        actual_hole_radius = result[HOLE_RADIUS]
                        actual_sides_count = result[SIDES_COUNT]
                        actual_has_hole = result[HAS_HOLE]

                        # Log key parameters
                        logger.info(f"Task parameter check: Expected prism circumscribed radius={expected_prism_radius}, height={expected_prism_height}, sides={expected_sides_count}")
                        logger.info(f"Expected center hole: radius={expected_hole_radius}")
                        logger.info(f"Actual parameters: Actual prism circumscribed radius={actual_prism_radius}, height={actual_prism_height}, sides={actual_sides_count}")
                        logger.info(f"Actual center hole: radius={actual_hole_radius}, has hole: {actual_has_hole}")

                        try:
                            # Try to get numeric part (handling possible units)
                            actual_prism_radius_value = float(str(actual_prism_radius).split()[0]) if isinstance(actual_prism_radius, str) else float(actual_prism_radius)
                            actual_prism_height_value = float(str(actual_prism_height).split()[0]) if isinstance(actual_prism_height, str) else float(actual_prism_height)
                            actual_hole_radius_value = float(str(actual_hole_radius).split()[0]) if isinstance(actual_hole_radius, str) else float(actual_hole_radius)
                            actual_sides_count_value = int(actual_sides_count)
                            
                            # Allow a certain margin of error (0.01%)
                            prism_radius_error = abs((actual_prism_radius_value - expected_prism_radius) / expected_prism_radius) <= 0.0001
                            prism_height_error = abs((actual_prism_height_value - expected_prism_height) / expected_prism_height) <= 0.0001
                            hole_radius_error = abs((actual_hole_radius_value - expected_hole_radius) / expected_hole_radius) <= 0.0001
                            sides_count_error = actual_sides_count_value == expected_sides_count
                            
                            has_hole_correct = actual_has_hole
                        except Exception as e:
                            logger.error(f"Parameter comparison error: {str(e)}")
                            prism_radius_error = False
                            prism_height_error = False
                            hole_radius_error = False
                            sides_count_error = False
                            has_hole_correct = False
                        
                        prism_correct = prism_radius_error and prism_height_error and sides_count_error
                        hole_correct = hole_radius_error and has_hole_correct
                        
                        if prism_correct and hole_correct:
                            # Update second key step status
                            updates.append({
                                'status': 'key_step',
                                'index': 2,
                                'name': 'Created octagonal prism with central circular hole and saved successfully'
                            })
                            
                            # Task completed successfully
                            updates.append({
                                'status': 'success',
                                'reason': 'Successfully created an octagonal prism with central circular hole according to requirements and saved it'
                            })
                        else:
                            logger.warning(f"Parameter validation failed: " + 
                                          f"Octagonal prism correct: {prism_correct}, " +
                                          f"Central circular hole correct: {hole_correct}")
                
            elif event_type == ERROR:
                error_type = payload.get("error_type", "unknown")
                error_message = payload.get("message", "Unknown error")
                
                logger.error(f"Hook script error ({error_type}): {error_message}")
                
                # Record error event
                updates.append({
                    'status': 'error',
                    'type': error_type,
                    'message': error_message
                })
                
    elif message.get('type') == 'error':
        logger.error(f"Hook script error: {message.get('stack', '')}")
        
        # Record error event
        updates.append({
            'status': 'error',
            'type': 'script_error',
            'message': message.get('stack', 'Unknown error')
        })
    
    return updates if updates else None
