#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
QGIS Layer Opacity Configuration Event Handler
Responsible for processing events generated by hook scripts and updating evaluation metrics
"""

import os
from typing import Dict, Any, Optional, List

def message_handler(message: Dict[str, Any], logger: Any, task_parameter: Dict[str, Any]) -> Optional[List[Dict[str, Any]]]:
    """
    Process messages received from hook scripts
    
    Args:
        message: Frida message object
        logger: Logger object
        task_parameter: Task parameters
        
    Returns:
        Optional[List[Dict[str, Any]]]: Returns status list if task status is updated, otherwise None
    """

    # Process message
    if message.get('type') == 'send' and 'payload' in message:
        payload = message['payload']
        
        # Check if event type is included
        if 'event' in payload:
            event_type = payload['event']
            logger.debug(f"Event received: {event_type}")
            
            # Handle specific events
            if event_type == "script_initialized":
                logger.info(f"Hook script initialized: {payload.get('message', '')}")
                return None
                
            elif event_type == "set_function_found":
                logger.info(f"Found opacity setting function: {payload.get('address', '')}")
                return None
                
            elif event_type == "layer_set":
                layer_name = payload.get("name", "")
                logger.info(f"Detected layer opacity setting: {layer_name}")
                
                # Check if layer name matches expectation
                expected_layer_name = task_parameter.get("LayerName", "")
                logger.debug(f"Comparing layer names - Detected: {layer_name}, Expected: {expected_layer_name}")
                
                # Determine if detected layer name matches expectation
                if expected_layer_name.lower() in layer_name.lower():
                    logger.info("Layer name for opacity setting matches expected target!")                    
                    # Return key step
                    return [{"status": "key_step", "index": 1, "name": "Operating on expected layer"}]
                else:
                    logger.info(f"Layer name for opacity setting does not match expectation. Expected: {expected_layer_name}, Actual: {layer_name}")
                
            elif event_type == "opacity_set":
                layer_name = payload.get("layer", "")
                opacity = payload.get("opacity", "")
                raw_opacity = payload.get("opacity_raw", 0)
                
                logger.info(f"Detected opacity setting for layer {layer_name}: {opacity}%")
                
                # Check if layer name and opacity match expectations
                expected_layer_name = task_parameter.get("LayerName", "")
                expected_opacity = float(task_parameter.get("opacity", "0"))
                
                # Convert detected opacity to float for comparison
                detected_opacity = float(opacity)
                
                # Allow 1% margin of error
                opacity_match = abs(detected_opacity - expected_opacity) <= 1
                layer_match = expected_layer_name.lower() in layer_name.lower()
                
                if layer_match and opacity_match:
                    logger.info(f"Layer opacity setting matches expectation! Layer: {layer_name}, Opacity: {opacity}%")                    
                    # Return key step and success status
                    return [
                        {"status": "key_step", "index": 2, "name": "Expected opacity set"},
                        {"status": "success", "reason": f"Successfully set opacity for layer {layer_name} to {opacity}%"}
                    ]
                else:
                    if not layer_match:
                        logger.info(f"Layer does not match expectation. Expected: {expected_layer_name}, Actual: {layer_name}")
                    if not opacity_match:
                        logger.info(f"Opacity does not match expectation. Expected: {expected_opacity}%, Actual: {opacity}%")
                
            elif event_type == "error":
                error_type = payload.get("error_type", "unknown")
                error_message = payload.get("message", "Unknown error")
                logger.error(f"Hook script error ({error_type}): {error_message}")
                
                # Return error status
                return [{
                    "status": "error",
                    "type": error_type,
                    "message": error_message
                }]
                
    elif message.get('type') == 'error':
        stack = message.get('stack', '')
        logger.error(f"Hook script error: {stack}")
        
        # Return error status
        return [{
            "status": "error",
            "type": "script_error",
            "message": "Hook script execution error",
            "stack_trace": stack
        }]
    
    return None
