#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
FreeCAD Disk with Torus Groove Event Handler
Responsible for handling events generated by the hook script and updating evaluation metrics
"""

from typing import Dict, Any, Optional, List

# Event type constants
SCRIPT_INITIALIZED = "script_initialized"
FUNCTION_NOT_FOUND = "function_not_found"
FUNCTION_FOUND = "function_found"
FUNCTION_CALLED = "function_called"
FUNCTION_KEY_WORD_DETECTED = "function_key_word_detected"
ERROR = "error"
HOOK_INSTALLED = "hook_installed"

# Keyword-related constants
DISK_RADIUS = "disk_radius"
DISK_HEIGHT = "disk_height"
TORUS_RADIUS1 = "torus_radius1"
TORUS_RADIUS2 = "torus_radius2"
TORUS_ANGLE1 = "torus_angle1"
TORUS_ANGLE2 = "torus_angle2"
TORUS_ANGLE3 = "torus_angle3"
HAS_TORUS_CUT = "has_torus_cut"

def execute_python_code(code: str, logger: Any) -> Dict[str, Any]:
    """
    Execute Python code and return the result

    Args:
        code: Python code to execute
        logger: Logger instance

    Returns:
        Dict[str, Any]: Execution result
    """
    try:
        # Create a new namespace to execute the code
        namespace = {}
        exec(code, namespace)
        result = namespace.get('result', None)

        if result is None:
            logger.warning("Disk with torus groove object not found")
            return None

        # Validate result format
        required_keys = [
            DISK_RADIUS, DISK_HEIGHT, 
            TORUS_RADIUS1, TORUS_RADIUS2, 
            TORUS_ANGLE1, TORUS_ANGLE2, 
            TORUS_ANGLE3, HAS_TORUS_CUT
        ]
        if not all(key in result for key in required_keys):
            logger.error(f"Result is missing required keys: {required_keys}")
            return None

        return result
    except Exception as e:
        logger.error(f"Error executing Python code: {str(e)}")
        return None

def message_handler(message: Dict[str, Any], logger: Any, task_parameter: Dict[str, Any]) -> Optional[List[Dict[str, Any]]]:
    """
    Handle messages received from the hook script

    Args:
        message: Frida message object
        logger: Logger instance
        task_parameter: Task parameters

    Returns:
        Optional[List[Dict[str, Any]]]: List of status updates, or None if no updates
    """
    updates = []

    if message.get('type') == 'send' and 'payload' in message:
        payload = message['payload']

        if 'event' in payload:
            event_type = payload['event']
            logger.debug(f"Received event: {event_type}")

            if event_type == SCRIPT_INITIALIZED:
                logger.info(f"Hook script initialized: {payload.get('message', '')}")

            elif event_type == FUNCTION_FOUND:
                logger.info(f"Function found: {payload.get('address', '')}")

            elif event_type == FUNCTION_CALLED:
                logger.info(f"Function called: {payload.get('message', '')}")
                # Update the status of the first key step
                updates.append({
                    'status': 'key_step',
                    'index': 1,
                    'name': 'Save Document'
                })

            elif event_type == FUNCTION_KEY_WORD_DETECTED:
                # Execute Python code and get the result
                code = payload.get('code', '')
                filename = payload.get('filename', '')
                expected_path = task_parameter.get("source_path", "") + task_parameter.get("filename", "")
                logger.info(f"Keyword detected, document path: {filename}, expected document path: {expected_path}")

                if filename == expected_path:
                    result = execute_python_code(code, logger)
                    if result:
                        # Check if the disk with torus groove parameters meet expectations
                        expected_disk_radius = task_parameter.get(DISK_RADIUS, 30.0)
                        expected_disk_height = task_parameter.get(DISK_HEIGHT, 10.0)
                        expected_torus_radius1 = task_parameter.get(TORUS_RADIUS1, 20.0)
                        expected_torus_radius2 = task_parameter.get(TORUS_RADIUS2, 5.0)
                        expected_torus_angle1 = task_parameter.get(TORUS_ANGLE1, 0.0)
                        expected_torus_angle2 = task_parameter.get(TORUS_ANGLE2, 0.0)
                        expected_torus_angle3 = task_parameter.get(TORUS_ANGLE3, 360.0)

                        actual_disk_radius = result[DISK_RADIUS]
                        actual_disk_height = result[DISK_HEIGHT]
                        actual_torus_radius1 = result[TORUS_RADIUS1]
                        actual_torus_radius2 = result[TORUS_RADIUS2]
                        actual_torus_angle1 = result[TORUS_ANGLE1]
                        actual_torus_angle2 = result[TORUS_ANGLE2]
                        actual_torus_angle3 = result[TORUS_ANGLE3]
                        actual_has_torus_cut = result[HAS_TORUS_CUT]

                        # Log key parameters
                        logger.info(f"Task parameter check: Expected disk radius={expected_disk_radius}, height={expected_disk_height}")
                        logger.info(f"Expected torus groove: Radius1={expected_torus_radius1}, Radius2={expected_torus_radius2}, " +
                                   f"Angle1={expected_torus_angle1}, Angle2={expected_torus_angle2}, " +
                                   f"Angle3={expected_torus_angle3}")
                        logger.info(f"Actual parameters: Actual disk radius={actual_disk_radius}, height={actual_disk_height}")
                        logger.info(f"Actual torus groove: Radius1={actual_torus_radius1}, Radius2={actual_torus_radius2}, " +
                                   f"Angle1={actual_torus_angle1}, Angle2={actual_torus_angle2}, " +
                                   f"Angle3={actual_torus_angle3}, " +
                                   f"Has torus groove: {actual_has_torus_cut}")

                        # Convert values with possible units to floats
                        try:
                            # Attempt to extract numeric part (handle possible units)
                            actual_disk_radius_value = float(str(actual_disk_radius).split()[0]) if isinstance(actual_disk_radius, str) else float(actual_disk_radius)
                            actual_disk_height_value = float(str(actual_disk_height).split()[0]) if isinstance(actual_disk_height, str) else float(actual_disk_height)

                            actual_torus_radius1_value = float(str(actual_torus_radius1).split()[0]) if isinstance(actual_torus_radius1, str) else float(actual_torus_radius1)
                            actual_torus_radius2_value = float(str(actual_torus_radius2).split()[0]) if isinstance(actual_torus_radius2, str) else float(actual_torus_radius2)
                            actual_torus_angle1_value = float(str(actual_torus_angle1).split()[0]) if isinstance(actual_torus_angle1, str) else float(actual_torus_angle1)
                            actual_torus_angle2_value = float(str(actual_torus_angle2).split()[0]) if isinstance(actual_torus_angle2, str) else float(actual_torus_angle2)
                            actual_torus_angle3_value = float(str(actual_torus_angle3).split()[0]) if isinstance(actual_torus_angle3, str) else float(actual_torus_angle3)

                            # Allow a certain margin of error (0.01%)
                            disk_radius_error = abs((actual_disk_radius_value - expected_disk_radius) / expected_disk_radius) <= 0.0001
                            disk_height_error = abs((actual_disk_height_value - expected_disk_height) / expected_disk_height) <= 0.0001

                            torus_radius1_error = abs((actual_torus_radius1_value - expected_torus_radius1) / expected_torus_radius1) <= 0.0001
                            torus_radius2_error = abs((actual_torus_radius2_value - expected_torus_radius2) / expected_torus_radius2) <= 0.0001

                            # Angles may have multiple representations, allow larger error
                            torus_angle1_error = abs(actual_torus_angle1_value - expected_torus_angle1) <= 1.0
                            torus_angle2_error = abs(actual_torus_angle2_value - expected_torus_angle2) <= 1.0
                            torus_angle3_error = abs(actual_torus_angle3_value - expected_torus_angle3) <= 1.0

                            has_torus_cut_correct = actual_has_torus_cut
                        except Exception as e:
                            logger.error(f"Error comparing parameters: {str(e)}")
                            disk_radius_error = False
                            disk_height_error = False
                            torus_radius1_error = False
                            torus_radius2_error = False
                            torus_angle1_error = False
                            torus_angle2_error = False
                            torus_angle3_error = False
                            has_torus_cut_correct = False

                        disk_correct = disk_radius_error and disk_height_error
                        torus_correct = (torus_radius1_error and torus_radius2_error and
                                        torus_angle1_error and torus_angle2_error and
                                        torus_angle3_error and has_torus_cut_correct)

                        if disk_correct and torus_correct:
                            # Update the status of the second key step
                            updates.append({
                                'status': 'key_step',
                                'index': 2,
                                'name': 'Create disk with torus groove and save successfully'
                            })

                            # Task successfully completed
                            updates.append({
                                'status': 'success',
                                'reason': 'Successfully created a disk with torus groove that meets the requirements and saved it'
                            })
                        else:
                            logger.warning(f"Parameter validation failed: " + 
                                          f"Disk correct: {disk_correct}, " +
                                          f"Torus groove correct: {torus_correct}")

            elif event_type == ERROR:
                error_type = payload.get("error_type", "unknown")
                error_message = payload.get("message", "Unknown error")

                logger.error(f"Hook script error ({error_type}): {error_message}")

                # Record error event
                updates.append({
                    'status': 'error',
                    'type': error_type,
                    'message': error_message
                })

    elif message.get('type') == 'error':
        logger.error(f"Hook script error: {message.get('stack', '')}")

        # Record error event
        updates.append({
            'status': 'error',
            'type': 'script_error',
            'message': message.get('stack', 'Unknown error')
        })

    return updates if updates else None
