#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
QGIS Zoom to Layer Event Handler
Responsible for processing events generated by hook scripts and updating evaluation metrics
"""

import os
from typing import Dict, Any, Optional, List

def message_handler(message: Dict[str, Any], logger: Any, task_parameter: Dict[str, Any]) -> Optional[List[Dict[str, Any]]]:
    """
    Process messages received from hook scripts
    
    Args:
        message: Frida message object
        logger: Logger
        task_parameter: Task parameters
        
    Returns:
        Optional[List[Dict[str, Any]]]: Return status list if task status is updated, otherwise return None
    """

    # Process message
    if message.get('type') == 'send' and 'payload' in message:
        payload = message['payload']
        
        # Check if event type is included
        if 'event' in payload:
            event_type = payload['event']
            logger.debug(f"Received event: {event_type}")
            
            # Handle specific events
            if event_type == "script_initialized":
                logger.info(f"Hook script initialized: {payload.get('message', '')}")
                return None
                
            elif event_type == "zoom_function_found":
                logger.info(f"Found zoom function: {payload.get('address', '')}")
                return None
                
            elif event_type == "layer_zoomed":
                layer_name = payload.get("name", "")
                logger.info(f"Detected zoom to layer: {layer_name}")
                
                # Check if layer name matches expectation
                expected_layer_name = task_parameter.get("LayerName", "")
                logger.debug(f"Comparing layer names - Detected: {layer_name}, Expected: {expected_layer_name}")
                
                # Determine if detected layer name matches expectation
                # Note: Partial or exact matching can be performed depending on requirements
                if expected_layer_name.lower() in layer_name.lower():
                    logger.info("Zoomed layer name matches expected target!")                    
                    # Return key step and success status
                    return [
                        {"status": "key_step", "index": 1, "name": "Expected layer zoomed"},
                        {"status": "success", "reason": f"Successfully zoomed to layer: {layer_name}"}
                    ]
                else:
                    logger.info(f"Zoomed layer name does not match expectation. Expected: {expected_layer_name}, Actual: {layer_name}")
                
            elif event_type == "error":
                error_type = payload.get("error_type", "unknown")
                error_message = payload.get("message", "Unknown error")
                logger.error(f"Hook script error ({error_type}): {error_message}")
                
                # Return error status
                return [{
                    "status": "error",
                    "type": error_type,
                    "message": error_message
                }]
                
    elif message.get('type') == 'error':
        stack = message.get('stack', '')
        logger.error(f"Hook script error: {stack}")
        
        # Return error status
        return [{
            "status": "error",
            "type": "script_error",
            "message": "Hook script execution error",
            "stack_trace": stack
        }]
    
    return None
