#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
QGIS Add Raster Layer Event Handler
Responsible for processing events generated by hook scripts and updating evaluation metrics
"""

import os
from typing import Dict, Any, Optional, List

def message_handler(message: Dict[str, Any], logger: Any, task_parameter: Dict[str, Any]) -> Optional[List[Dict[str, Any]]]:
    """
    Process messages received from hook scripts
    
    Args:
        message: Frida message object
        logger: Logger object
        task_parameter: Task parameters
        
    Returns:
        Optional[List[Dict[str, Any]]]: Returns status list if task status is updated, otherwise None
    """

    # Process message
    if message.get('type') == 'send' and 'payload' in message:
        payload = message['payload']
        
        # Check if event type is included
        if 'event' in payload:
            event_type = payload['event']
            logger.debug(f"Event received: {event_type}")
            
            # Handle specific events
            if event_type == "script_initialized":
                logger.info(f"Hook script initialized: {payload.get('message', '')}")
                return None
                
            elif event_type == "addRasterLayer_function_found":
                logger.info(f"Found addRasterLayer function: {payload.get('address', '')}")
                return None
                
            elif event_type == "raster_layer_added":
                detected_uri = payload.get("uri", "")
                logger.info(f"Detected raster layer addition: {detected_uri}")
                
                # Check if layer path matches expectation
                expected_path = task_parameter.get("rasterLayerPath", "")
                
                # Normalize paths for comparison
                detected_uri_norm = os.path.normpath(detected_uri)
                expected_path_norm = os.path.normpath(expected_path)
                logger.debug(f"Normalized paths - Detected: {detected_uri_norm}, Expected: {expected_path_norm}")
                
                # Determine if detected layer path matches expectation
                if detected_uri_norm == expected_path_norm or detected_uri.endswith(expected_path):
                    logger.info("Raster layer path matches expected target!")                    
                    # Return key step and success status
                    return [
                        {"status": "key_step", "index": 1, "name": "Expected raster layer added"},
                        {"status": "success", "reason": f"Successfully added raster layer: {detected_uri}"}
                    ]
                else:
                    logger.info(f"Added raster layer path does not match expectation. Expected: {expected_path}, Actual: {detected_uri}")
                
            elif event_type == "error":
                error_type = payload.get("error_type", "unknown")
                error_message = payload.get("message", "Unknown error")
                logger.error(f"Hook script error ({error_type}): {error_message}")
                
                # Return error status
                return [{
                    "status": "error",
                    "type": error_type,
                    "message": error_message
                }]
                
    elif message.get('type') == 'error':
        stack = message.get('stack', '')
        logger.error(f"Hook script error: {stack}")
        
        # Return error status
        return [{
            "status": "error",
            "type": "script_error",
            "message": "Hook script execution error",
            "stack_trace": stack
        }]
    
    return None
